# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='fio',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xd0\xa4\xd0\x98\xd0\x9e'),
        ),
    ]
