# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0003_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': '\u0424\u0438\u043b\u0438\u0430\u043b', 'verbose_name_plural': '\u0424\u0438\u043b\u0438\u0430\u043b\u044b'},
        ),
    ]
