# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0004_auto_20161116_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fio',
            field=models.CharField(max_length=200, verbose_name=b'\xd0\xa4\xd0\x98\xd0\x9e'),
        ),
    ]
