# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0005_auto_20161116_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name=b'\xd0\xa4\xd0\x98\xd0\x9e')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subd.Filial')),
            ],
            options={
                'verbose_name': '\u0410\u0433\u0435\u043d\u0442',
                'verbose_name_plural': '\u0410\u0433\u0435\u043d\u0442\u044b',
            },
        ),
    ]
