# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0006_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subd.Filial', verbose_name=b'\xd1\x84\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xb0\xd0\xbb'),
        ),
    ]
