# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0007_auto_20161116_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name=b'\xd0\xa4\xd0\x98\xd0\x9e')),
                ('type', models.CharField(choices=[(b'A', b'\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe\xd1\x82\xd1\x80\xd0\xb0\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 \xd0\xbe\xd1\x82 \xd1\x83\xd0\xb3\xd0\xbe\xd0\xbd\xd0\xb0'), (b'H', b'\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb5\xd0\xb5 \xd0\xb8\xd0\xbc\xd1\x83\xd1\x89\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'), (b'M', b'\xd0\x94\xd0\xbe\xd0\xb1\xd1\x80\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x86\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5')], max_length=1, verbose_name=b'\xd1\x82\xd0\xb8\xd0\xbf')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'\xd0\xa2\xd0\xb0\xd1\x80\xd0\xb8\xd1\x84 %')),
                ('date', models.DateTimeField(verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subd.Agent', verbose_name=b'\xd0\xb0\xd0\xb3\xd0\xb5\xd0\xbd\xd1\x82')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subd.Client', verbose_name=b'\xd0\xba\xd0\xbb\xd0\xb8\xd0\xb5\xd0\xbd\xd1\x82')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subd.Filial', verbose_name=b'\xd1\x84\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xb0\xd0\xbb')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0440\u0430\u043a\u0442\u044b',
            },
        ),
    ]
