# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0008_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='fio',
        ),
    ]
