# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0009_remove_contract_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb8\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f'),
            preserve_default=False,
        ),
    ]
