# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subd', '0010_contract_comission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '\u0414\u043e\u0433\u043e\u0432\u043e\u0440', 'verbose_name_plural': '\u0414\u043e\u0433\u043e\u0432\u043e\u0440\u044b'},
        ),
    ]
